language: java
dist: trusty
addons:
  sonarcloud:
    organization: "sonarcloud_organization_key"
    token:
      secure: *********
    branches:
      - master
      - maintenance
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sona
